### ISSUE TITLE
After setup there is no camera entity, but there is a solution!

### ISSUE THREAD

**Issue by Creo2005** [thehiddentruth/home-assistant-moonraker#1]
I solved it by adding a camera through the interface: https://www.home-assistant.io/integrations/octoprint/

**Comment by kakemanx** [comment]
> I solved it by adding a camera through the interface: https://www.home-assistant.io/integrations/octoprint/

Did you get everything else to work?
I cant get ANY sensors or entities to show up in HA... 
I have copyed the moonraker.yaml to resources folder and updated IP's
... what am i missing :/
